-- UVT - INFO - INFO-EN
call profile_insert(@faculty_id, 'Informatică', 'Informatică - En', 'Engleză', 'Licență', 2, @profile_id);
-- UVT - INFO - INFO-EN - An 1
call course_insert(@profile_id, 'Algoritmică', 'Algoritmică', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Programare 1', 'Programare 1', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Bazele informaticii', 'Bazele informaticii', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Algebră', 'Algebră', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Analiză – Calcul diferențial și integral', 'Analiză - CDI', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Birotică', 'Birotică', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Limba engleză - 1', 'Limba engleză', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Limba franceză - 1', 'Limba franceză', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Limba germană - 1', 'Limba germană', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Structuri de date', 'SD', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Arhitectura calculatoarelor', 'AC', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Programare 2', 'Programare 2', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Limbaje formale și teoria automatelor', 'LFTA', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Geometrie', 'Geometrie', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Comunicare', 'Comunicare', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Stagiu de practică - 1', 'Stagiu de practică', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Proiecte", 0, 2, @folder_id);
call course_insert(@profile_id, 'Metode și practici în informatică', 'MPI', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Limba engleză - 2', 'Limba engleză', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Limba franceză - 2', 'Limba franceză', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Limba germană - 2', 'Limba germană', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
-- UVT - INFO - INFO-EN - An 2
call course_insert(@profile_id, 'Teoria grafurilor și combinatorică', 'TGC', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Sisteme de operare 1', 'SO 1', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Baze de date 1', 'BD 1', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Programare 3', 'Programare 3', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Structuri de date avansate', 'SDA', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Programare logică', 'Programare logică', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Elemente de web design', 'EWD', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Cultura europeană', 'Cultura europeană', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Proiect individual', 'Proiect individual', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Proiecte", 0, 2, @folder_id);
call course_insert(@profile_id, 'Limba engleză - 3', 'Limba engleză', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Limba franceză - 3', 'Limba franceză', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Limba germană - 3', 'Limba germană', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Reţele de calculatoare', 'Reţele', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Probabilități și statistică', 'PS', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Baze de date 2', 'BD 2', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Inginerie soft', 'Inginerie soft', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Proiect colectiv', 'Proiect colectiv', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Proiecte", 0, 2, @folder_id);
call course_insert(@profile_id, 'Stagiu de practică - 2', 'Practică', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Proiecte", 0, 2, @folder_id);
call course_insert(@profile_id, 'Programare funcțională', 'PF', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Sisteme de operare 2', 'SO 2', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Limba engleză - 4', 'Limba engleză', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Limba franceză - 4', 'Limba franceză', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Limba germană - 4', 'Limba germană', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
-- UVT - INFO - INFO-EN - An 3
call course_insert(@profile_id, 'Inteligență artificială', 'IA', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Tehnologii Web', 'Tehnologii Web', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Ecuații diferențiale și cu derivate parțiale', 'EDDP', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Informatică de gestiune', 'IG', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Managementul proiectelor informatice', 'MPI', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Securitate și criptografie', 'SC', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Grafică și interfețe utilizator', 'GIU', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Metode numerice', 'Metode numerice', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Administrarea rețelelor', 'Administrarea rețelelor', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Programare concurentă și distribuită', 'PCD', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Sisteme inteligente', 'SI', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Teoria informației', 'Teoria informației', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);