DROP TABLE IF EXISTS Comment;		
		
CREATE TABLE Comment (
  ObjectId INTEGER NOT NULL,
  SubjectId INTEGER NOT NULL,
  UserId INTEGER NOT NULL,
  Text VARCHAR(250) NOT NULL,
  CreationDate DATETIME NOT NULL,
  PRIMARY KEY (ObjectId)
);

ALTER TABLE Comment ADD FOREIGN KEY (ObjectId) REFERENCES Object(ObjectId);
ALTER TABLE Comment ADD FOREIGN KEY (SubjectId) REFERENCES Object(ObjectId);
ALTER TABLE Comment ADD FOREIGN KEY (UserId) REFERENCES Users(UserId);
