USE studbox;

DROP TABLE IF EXISTS Course;
		
CREATE TABLE Course (
  ObjectId INTEGER NOT NULL,
  ProfileId INTEGER NOT NULL,  
  DefaultFolderId INTEGER NOT NULL,
  Name VARCHAR(150) NOT NULL,
  ShortName VARCHAR(30) NOT NULL,
  ViewNo INTEGER NOT NULL DEFAULT 0,
  OwnerId INTEGER NOT NULL,
  CreationDate DATETIME NOT NULL,
  LastModifiedDate DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (ObjectId),
  UNIQUE KEY (ProfileId, Name)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

ALTER TABLE Course ADD FOREIGN KEY (ObjectId) REFERENCES Object(ObjectId);
ALTER TABLE Course ADD FOREIGN KEY (ProfileId) REFERENCES Profile(ObjectId);
ALTER TABLE Course ADD FOREIGN KEY (DefaultFolderId) REFERENCES Folder(ObjectId);
ALTER TABLE Course ADD FOREIGN KEY (OwnerId) REFERENCES Users(UserId);