USE studbox;

DROP TABLE IF EXISTS File;
		
CREATE TABLE File (
  ObjectId INTEGER NOT NULL,
  FolderId INTEGER NOT NULL,
  Name VARCHAR(50) NOT NULL,
  ContentType VARCHAR(20) NOT NULL,
  ContentLength INTEGER NOT NULL,
  OwnerId INTEGER NOT NULL,
  Path VARCHAR(200) NOT NULL,
  CreationDate DATETIME NOT NULL,
  LastModifiedDate DATETIME NULL DEFAULT NULL,
  ViewNo INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (ObjectId),
  UNIQUE KEY(FolderId, Name)
);

ALTER TABLE File ADD FOREIGN KEY (ObjectId) REFERENCES Object(ObjectId);
ALTER TABLE File ADD FOREIGN KEY (FolderId) REFERENCES Folder(ObjectId);
ALTER TABLE File ADD FOREIGN KEY (OwnerId) REFERENCES Users(UserId);