USE studbox;

DROP TABLE IF EXISTS Folder;

CREATE TABLE Folder (
  ObjectId INTEGER NOT NULL,
  ParentFolderId INTEGER NULL,
  Name VARCHAR(30) NOT NULL,
  IsCourse bit(1) NOT NULL DEFAULT 0,
  ViewNo INTEGER NOT NULL DEFAULT 0,
  OwnerId INTEGER NOT NULL,    
  CreationDate DATETIME NOT NULL,
  LastModifiedDate DATETIME NULL DEFAULT NULL,  
  PRIMARY KEY (ObjectId)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

ALTER TABLE Folder ADD FOREIGN KEY (ObjectId) REFERENCES Object(ObjectId);
ALTER TABLE Folder ADD FOREIGN KEY (ParentFolderId) REFERENCES Folder(ObjectId);
ALTER TABLE Folder ADD FOREIGN KEY (OwnerId) REFERENCES Users(UserId);