USE studbox;

DROP TABLE IF EXISTS Users;
		
CREATE TABLE Users (
  UserId INTEGER NOT NULL AUTO_INCREMENT,
  Username VARCHAR(20) NOT NULL,
  Password VARCHAR(50) NOT NULL,
  FirstName VARCHAR(25) NOT NULL,
  LastName VARCHAR(25) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Sex CHAR NOT NULL,
  Birthdate DATE NOT NULL,
  CreationDate DATETIME NOT NULL,
  LockDate DATETIME NULL DEFAULT NULL,
  Status TINYINT NOT NULL DEFAULT 0,
  UseNotifications bit(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (UserId), 
  UNIQUE KEY(Username),
  UNIQUE KEY(Email)
);