-- UBB - INFO - INFO-EN
call profile_insert(@faculty_id, 'Informatică', 'Informatică - En', 'Engleză', 'Licenţă', 2, @profile_id);
-- UBB - INFO - INFO-EN - An 1
call course_insert(@profile_id, 'Arhitectura sistemelor de calcul', 'ASC', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Fundamentele programării', 'FP', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Logică computaţională', 'LC', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Comunicare şi dezvoltare profesională în informatică', 'CDPI', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
call course_insert(@profile_id, 'Algebră', 'Algebră', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Analiză matematică', 'Analiză', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Limba engleză - 1', 'Engleză', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Sisteme de operare', 'SO', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
call course_insert(@profile_id, 'Programare orientată obiect', 'POO', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Structuri de date şi algoritmi', 'SDA', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Geometrie', 'Geometrie', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Sisteme dinamice', 'SD', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Limba engleză - 2', 'Engleză', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
-- UBB - INFO - INFO-EN - An 2
call course_insert(@profile_id, 'Metode avansate de programare', 'MAP', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Sisteme de operare distribuite', 'SOD', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
call course_insert(@profile_id, 'Baze de date', 'BD', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Programare logică şi funcţională', 'PLF', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Probabilităţi şi statistică', 'Statistică', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Algoritmica grafelor', 'AG', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Ingineria sistemelor soft', 'ISS', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Gestiunea tranzacţiilor şi baze de date distribuite', 'GTBDD', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Inteligenţă artificială', 'IA', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Reţele de calculatoare', 'Reţele', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);	
call course_insert(@profile_id, 'Proiect individual', 'Proiect individual', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);	
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Proiecte", 0, 2, @folder_id);
call course_insert(@profile_id, 'Tehnici de optimizare', 'Tehnici de optimizare', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Aplicaţii ale logicii', 'Aplicaţii ale logicii', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
call course_insert(@profile_id, 'Programare orientată pe aspecte', 'POA', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
call course_insert(@profile_id, 'Geometrie computaţională', 'Geometrie computaţională', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
-- UBB - INFO - INFO-EN - An 3
call course_insert(@profile_id, 'Programare Web', 'Programare Web', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
call course_insert(@profile_id, 'Limbaje formale şi tehnici de compilare', 'LFTC', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Calcul evolutiv: algoritmi şi operatori', 'CEAO', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Criptografie cu cheie publică', 'Criptografie', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Baze de date spaţiale', 'BDS', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Prelucrarea cunoştinţelor', 'PC', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Protocoale specializate în reţele de calculatoare', 'PSRC', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Realitate virtuală', 'Realitate virtuală', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Modele pentru componentele soft', 'MCS', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Medii de proiectare şi programare', 'MPP', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
call course_insert(@profile_id, 'Verificarea şi validarea sistemelor soft', 'VVSS', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Practic", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Seminarii", 0, 2, @folder_id);
call course_insert(@profile_id, 'Calcul numeric', 'Calcul numeric', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Proiecte", 0, 2, @folder_id);
call course_insert(@profile_id, 'Comunicaţii audio-video în reţele de mare viteză', 'Comunicaţii audio-video', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Aplicaţii multimedia peste web', 'Aplicaţii multimedia', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Proiectare web şi optimizare', 'PWO', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Proiectare avansată de compilatoare', 'PAC', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Aspecte Pragmatice în programare', 'APP', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Prelucrarea informaţiilor într-o organizaţie', 'PIO', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Documentaţie", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Examene", 0, 2, @folder_id);
	call folder_insert(@default_folder_id, "Laboratoare", 0, 2, @folder_id);
call course_insert(@profile_id, 'Istoria matematicii', 'Istoria matematicii', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
call course_insert(@profile_id, 'Istoria informaticii', 'Istoria informaticii', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);
call course_insert(@profile_id, 'Metodologia documentării şi elaborării unei lucrări ştiinţifice', 'MDELS', 2, @course_id, @default_folder_id);
	call folder_insert(@default_folder_id, "Cursuri", 0, 2, @folder_id);